version: '3.9'


services:

  web:
    container_name: flask_web
    image: flask_web
    secrets:
      - db-password
    ports:
      - "5000:5000"
      - "8090:5000"
    env_file:
      - pure_docker_compose/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: flask_database
    image: mysql
    secrets:
      - db-password
    env_file:
      - pure_docker_compose/.db_env
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

secrets:
  db_password:
    file: pure_docker_compose/db-password
