version: '3.9'


services:

  web:
    container_name: flask_web 
    build:
      context: ../src
    secrets:
      - db-password
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: flask_database
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    secrets:
      - db-password
    env_file:
      - ./.db_env
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

secrets:
  db_password:
    file: db-password
