# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
strategy:
  type: Recreate

replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: 5.6
  containerPort: 3306


storage:
  storageClassName: manual
  resource:
    capacity: 2Gi


service:
  name: db
  type: ClusterIP
  port: 3306

