apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.resource.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
