apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask.fullname" . }}
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: flask-app
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          volumeMounts:
            - mountPath: "/etc/secrets/"
              name: db-password-secret
              readOnly: true

      volumes:
        - name: db-password-secret
          secret:
            secretName: secret-data
