apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-app
  ports:
    - name: flask
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
